version: "3.9"
services:
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb  
    volumes:
      - ~/volumes/mongodata/mongobin/data:/data/db
      - ~/volumes/mongodata/mongobin/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=US2022
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
          
  cityjokes:
    image: cityjokes     
    build: ./cityjokes
    container_name: cityjokes 
    links:
      - mongodb
    ports:
      - 4040:4040
    depends_on:     
      - mongodb  
    networks:
     - mnet
  
networks:
  mnet:
    driver: bridge
